<?php

// 超级管理员用户分组
define('USERGROUP_ADMIN', 1);

// 字符串类型
define('RAW_STRING', 0);
define('MD5_STRING', 1);

define('USER_UNBAN', 0);  // 正常用户
define('USER_BANED', 1);  // 禁用用户



// CS交互错误码
define('ERROR_ERR', -1);
define('ERROR_OK', 0);

define('ERROR_VERICODE_ERROR', 1200);
define('ERROR_USER_NOT_EXISTS', 1201);
define('ERROR_PASSWORD_ERROR', 1202);
define('ERROR_USER_BANED', 1203);
define('ERROR_USER_NOT_ALLOWED', 1204);
define('ERROR_PRIVATEAPI_TIME_EMPTY', 1301);
define('ERROR_PRIVATEAPI_APP_EMPTY', 1302);
define('ERROR_PRIVATEAPI_TOKEN_EMPTY', 1303);
define('ERROR_PRIVATEAPI_APP_NOT_EXIST', 1304);
define('ERROR_PRIVATEAPI_TIME_INVALID', 1305);
define('ERROR_PRIVATEAPI_TOKEN_INVALID', 1306);
define('ERROR_PRIVATEAPI_API_NOT_ALLOW', 1307);

//

